apiVersion: v1
kind: PersistentVolume
metadata:
  name: memento-redis-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/cj1/projects/docker-geth/data/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memento-redis-pv-claim
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi