apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go
        command: ['/bin/sh', '-c', '/opt/geth/config/entrypoint.sh']
        ports:
        - name: rpc-endpoint
          containerPort: 8545
        - name: ws-endpoint
          containerPort: 8546
        volumeMounts:
        - name: geth-datadir
          mountPath: /opt/geth/node
        - name: geth-config
          mountPath: /opt/geth/config
        - name: geth-secret
          mountPath: /opt/geth/secret
          readOnly: true
        # - name: geth-keystore
        #   mountPath: /opt/geth/node/keystore
        #   readOnly: true
      volumes:
      - name: geth-datadir
        persistentVolumeClaim:
          claimName: geth-pv-claim
      - name: geth-config
        configMap:
          name: geth-config
          defaultMode: 0755
      - name: geth-secret
        secret:
          secretName: geth-secret
      # - name: geth-keystore
      #   secret:
      #     secretName: geth-keystore    
