apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: default
spec:
  type: NodePort
  selector:
    app: geth
  sessionAffinity: ClientIP
  ports:
  - name: rpc-endpoint
    port: 8545
    protocol: TCP
    targetPort: 8545
    nodePort: 30356
  - name: ws-endpoint
    port: 8546
    protocol: TCP
    targetPort: 8546
    nodePort: 31037

  # - name: peer
  #   port: 30303
  #   protocol: UDP
  #   targetPort: 30303
