apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: default
spec:
  type: NodePort
  selector:
    app: geth
  ports:
  - name: rpc-endpoint
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: ws-endpoint
    port: 8546
    protocol: TCP
    targetPort: 8546
  # - name: peer
  #   port: 30303
  #   protocol: UDP
  #   targetPort: 30303
