apiVersion: v1
kind: Service
metadata:
  name: memento
  labels:
    app: memento
spec:
  type: NodePort
  ports:
   - name: dashboard
     port: 3000
   - name: explorer
     port: 3001
     nodePort: 30301
  selector:
   app: memento