apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: memento
  POSTGRES_USER: memento
  POSTGRES_PASSWORD: admin123
  # PGDATA: /var/lib/postgresql/data/pgdata
